export const DASMA_BARANGAYS = [
  "Burol I",
  "Burol II",
  "Burol III",
  "Datu Esmael (Bago-a-ingud)",
  "Emmanuel Bergado I",
  "Emmanuel Bergado II",
  "Fatima I",
  "Fatima II",
  "Fatima III",
  "H-2",
  "Langkaan I",
  "Langkaan II",
  "Luzviminda I",
  "Luzviminda II",
  "Paliparan I",
  "Paliparan II",
  "Paliparan III",
  "Sabang",
  "Salawag",
  "Salitran I",
  "Salitran II",
  "Salitran III",
  "Salitran IV",
  "Sampaloc I",
  "Sampaloc II",
  "Sampaloc III",
  "Sampaloc IV",
  "Sampaloc V",
  "San Agustin I",
  "San Agustin II",
  "San Agustin III",
  "San Andres I",
  "San Andres II",
  "San Antonio de Padua I",
  "San Antonio de Padua II",
  "San Dionisio (Barangay I)",
  "San Esteban (Barangay IV)",
  "San Francisco I",
  "San Francisco II",
  "San Isidro Labrador I",
  "San Isidro Labrador II",
  "San Jose",
  "San Juan (San Juan I)",
  "San Lorenzo Ruiz I",
  "San Lorenzo Ruiz II",
  "San Luis I",
  "San Luis II",
  "San Manuel I",
  "San Manuel II",
  "San Mateo",
  "San Miguel",
  "San Nicolas I",
  "San Nicolas II",
  "San Roque (Sta. Cristina II)",
  "San Simon (Barangay VII)",
  "Santa Cristina I",
  "Santa Cruz I",
  "Santa Cruz II",
  "Santa Fe",
  "Santa Lucia (San Juan II)",
  "Santa Maria (Barangay XX)",
  "Santo Cristo (Barangay II-A)",
  "Santo Nino I",
  "Santo Nino II",
  "Victoria Reyes",
  "Zone I (Poblacion)",
  "Zone I-A (Poblacion)",
  "Zone II (Poblacion)",
  "Zone III (Poblacion)",
  "Zone IV (Poblacion)",
  "Zone IV-A (Poblacion)",
  "Zone V (Poblacion)",
  "Zone VI (Poblacion)",
  "Zone VII (Poblacion)",
  "Zone VIII (Poblacion)",
  "Zone IX (Poblacion)",
  "Zone X (Poblacion)",
  "Zone XI (Poblacion)",
  "Zone XII (Poblacion)",
]
